### ISSUE TITLE
Erect remixes cannot be selected and Darnell (BF-mix) does not appear

### ISSUE THREAD

**Issue by biomseed** [MobilePorting/P-Slice-Mobile#10]
### Describe your bug here.

The difficulties only go from easy to hard

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't.

**Comment by mcagabe19** [comment]
upstream issue, they didn't add darnell bf mix

**Comment by biomseed** [comment]
Erect remixes cannot be selected
