### ISSUE TITLE
The P-Slice Engine shuts down abruptly when using a Lua script

### ISSUE THREAD

**Issue by Contra-Sakar** [MobilePorting/P-Slice-Mobile#3]
### Describe your bug here.

https://github.com/user-attachments/assets/c71d9934-0a22-4b2d-a4eb-1a95afc9b857

What happens is that any Lua script used with the P-Slice Engine shuts down abruptly without providing a reason. At first, I thought there was something wrong with the script, but when I use a script that is completely empty, the P-Slice Engine still shuts down abruptly when restarting the level.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
re-download from release

**Comment by Contra-Sakar** [comment]
The problem persists, and this only happens with Lua scripts; with Hx, everything works fine.

**Comment by mcagabe19** [comment]
issue shouldn't presist, can u send me the mod or lua u use

**Comment by Contra-Sakar** [comment]
As I explained, there's a bug in the P-Slice Engine that affects any Lua script. In the first version you released, Lua scripts with fewer than 434 lines worked fine. However, if a script had more than 435 lines, the engine would crash immediately when running it. Now, after your latest update, the bug has worsened — the engine crashes instantly with any Lua script, even an empty one. I demonstrated this in the video I uploaded.

**Comment by mcagabe19** [comment]
try this build when it's finishes
https://github.com/MobilePorting/P-Slice-Mobile/actions/runs/11268539331

**Comment by mcagabe19** [comment]
try this build when it's finishes
https://github.com/MobilePorting/P-Slice-Mobile/actions/runs/11268539331

**Comment by Contra-Sakar** [comment]
Everything works fine now, thank you ☺️
