### ISSUE TITLE
Error saving a chart or event

### ISSUE THREAD

**Issue by Contra-Sakar** [MobilePorting/P-Slice-Mobile#4]
### Describe your bug here.

When I try to save a chart, an error appears. This also happens if I only want to save the events, and this error shows up:

[file_open,assets\shared\data\tutorial\tutorial.json]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/cpp/_std/sys/io/File.write() [line 55]
/opt/hostedtoolcache/haxe/4.3.6/x64/std/cpp/_std/sys/io/File.saveContent() [line 39]
states/editors/ChartingState.saveChart() [line 4735]
states/editors/ChartingState.addFileTab() [line 3806]
backend/ui/PsychUIButton.update() [line 93]
flixel/group/FlxGroup.update() [line 151]
flixel/group/FlxSpriteGroup.update() [line 209]
backend/ui/PsychUITab.updateMenu() [line 47]
backend/ui/PsychUIBox.update() [line 166]
flixel/group/FlxGroup.update() [line 151]
backend/MusicBeatState.update() [line 170]
states/editors/ChartingState.update() [line 967]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
it doesn't happen on me at windows subsystem for android

**Comment by mcagabe19** [comment]
fixed on 1.2-patch1
