### ISSUE TITLE
The metadata.json does not work in mods

### ISSUE THREAD

**Issue by Contra-Sakar** [MobilePorting/P-Slice-Mobile#5]
### Describe your bug here.

The metadata.json doesn’t work in mods. Honestly, I have no idea if it’s an issue with the original P-Slice Engine or the mobile port itself.

In summary, the music preview doesn’t work.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
this is probably upstream issue, mobile port has nothing to do with it

**Comment by Contra-Sakar** [comment]
I understand; at least it’s not something that has a significant impact.
