### ISSUE TITLE
Custom Songs Bug

### ISSUE THREAD

**Issue by lspepinho** [MobilePorting/P-Slice-Mobile#7]
### Describe your bug here.

Sorry for the 2nd issue,but when i put a custom song in the mods folder,the engine crashes without logs

### Crash Log or logcat logs (if existing)

```bash
No logs.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No,I didn't

**Comment by mcagabe19** [comment]
I have to look tomorrow, it's 3 AM on me

**Comment by lspepinho** [comment]
I self compiled the engine and it now works. Closing the issue
