### ISSUE TITLE
P-Slice Engine 0.6.3

### ISSUE THREAD

**Issue by Z4CK1234** [MobilePorting/P-Slice-Mobile#8]
### What is your question?

I Think The P-Slice Engine In 0.6.3 Will Be Better Because 0.7.3 Is Buggy And Also Making The Lua Scripts Broken Alot... So If You Change Your Mind Porting The P-Slice To 0.6.3 I Appreciate It Also The Other People Who Downloads It, I'm Just Recommending That's All... I Was Really Hoping For The 0.6.3 Port...

**Comment by mcagabe19** [comment]
no.
