### ISSUE TITLE
Control error in freeplay, and FPS error above 60

### ISSUE THREAD

**Issue by Contra-Sakar** [MobilePorting/P-Slice-Mobile#9]
### Describe your bug here.

When a level is finished or you exit a level in freeplay, the freeplay buttons stop working.

Another issue is that when the FPS goes above 60, for example, to 120, the P-Slice Engine runs slow, especially in freeplay. It feels like everything is moving slowly, and even after playing and exiting a level, everything continues to be slow.

### Are you modding a build from source or with Lua?

I am not modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
fps is upstream issue and tpad issue is ours, I'll fix the tpad issue soon

**Comment by mcagabe19** [comment]
fixed, will be on releases tab after 1 hour

**Comment by Contra-Sakar** [comment]
The 2 problems I mentioned are still present.

**Comment by Contra-Sakar** [comment]
The problems
https://youtu.be/a1RBH2BcVW8?si=r6HlIRtVHJOysA6u

**Comment by mcagabe19** [comment]
idk, the first issue doesn't persist on my side and second issue is upstream issue, open issue to upstream about it

**Comment by mcagabe19** [comment]
okay second check, issue still persists

**Comment by mcagabe19** [comment]
now actually fixed
